### ISSUE TITLE
Option to change font used?

### ISSUE THREAD

**Issue by macintacos** [TheBlob42/idea-which-key#2]
I want to use a monospace font such as JetBrains Mono with this plugin. How can I do that? If I can't do that, can that be added?

I was just thinking about working on this kind of plugin, thanks for saving me the work 😅

**Comment by TheBlob42** [comment]
You're welcome :wink: 

Currently there is no option to use another font within the plugin, but in general I like the idea of making this configurable (if possible).

I use the `com.intellij.openapi.ui.popup.Balloon` class for the popup and pass it HTML as content, but I am uncertain if Intellij supports setting another font withing this HTML string and if so which ones would be allowed (all system fonts, a specific subset, ...) :thinking: 

I will check this out and keep you up to date

**Comment by TheBlob42** [comment]
My proposal is that you can set the variable `g:WhichKey_FontFamily` in your `.ideavimrc` to change the font used for the whole popup (keys, divider & description). I don't see any value in allowing different fonts for the different elements, but if you have good argument I am willing to listen :slightly_smiling_face: 

The value is passed to the CSS attribute `font-family`, therefore make sure that it is a valid string in this regard. Of course you need to have to have the font you want to use installed on your system :smile: but it should work as in a regular web browser

The default value is set to `monospace` since this makes the alignment in the popup look way better than it does currently

I have created a branch with the changes so you can see if it works for you.
I still need to add documentation to the `README`

What do you think?

**Comment by macintacos** [comment]
@TheBlob42 makes sense to me! I'm not sure if it'll make things more complicated, but would it be possible to edit the font size as well?

**Comment by TheBlob42** [comment]
This will require some re-works in the part which determines how many columns can be displayed without any line-breaks. But this is a section that I should have a look into anyways since there are fonts which are much wider than others :thinking: 

Should not be a huge issue. I will have a look into this and adapt the PR accordingly.

**Comment by TheBlob42** [comment]
@macintacos I have adopted the PR so that the font-size (in point) can be configured in the `.ideavimrc` file (the same size for all elements).

Have a look and test it :slightly_smiling_face:

**Comment by macintacos** [comment]
@TheBlob42 I'm unsure how I'd actually go about installing it from outside of the interface in the app, would you be able to push those changes so I can test it?

**Comment by TheBlob42** [comment]
I have packed you the build branch to a `jar` (in a .zip to be able to upload it) :slightly_smiling_face: 

You can install it from the Intellij Plugin menu:
*File -> Settings -> Plugins -> Install Plugin from Disk...*
(see also the `README` file under **Manual Installation**)

[FontConfigurationTest.zip](https://github.com/TheBlob42/idea-which-key/files/6045736/FontConfigurationTest.zip)

**Comment by macintacos** [comment]
Just tested it and it works the way I expect, great! Did it with the following settings and it looks great:

```vim
" which-key
let g:WhichKey_FontFamily = 'JetBrains Mono'
let g:WhichKey_FontSize = '16'
```

**Comment by TheBlob42** [comment]
Great to hear :+1: 

One more thing: The `g:WhichKey_FontSize` variable is actually not a string but a number, so it should be

```vim
let g:WhichKey_FontSize = 16
```
(without the single quotes)

But since the default font size for Intellij is `15` it is hard to notice :smile: 

I will merge the changes and then this is gonna be part of the next release `0.3`
