### ISSUE TITLE
plugin conflicts with surround

### ISSUE THREAD

**Issue by sosa-daniel** [TheBlob42/idea-which-key#48]
Hi. Loving the idea-which-key plugin so far, great work!

I noticed today that I was unable to use surround commands (ysiw and ys2w specifically). I commented out "set which-key" in .ideavimrc and restart the IDE it gets fixed. 

Any thoughts on what the problem could be or how to resolve it?

thanks

**Comment by sosa-daniel** [comment]
Ok I figured something out: 
If I uncomment the set command to enable the plugin and comment out only the line where I had set WhichKey_ProcessUnknownMappings to false and restart the IDE, then both plugins seem to work ok together.
So hopefully that narrows the scope of the problem just to that one setting.

**Comment by TheBlob42** [comment]
Ok this is a weird case.
In my debugging build it works fine, BUT this uses the "minimal" dependency for IdeaVIM which is `1.11.1`. So it seems that something has changed since then. In my work setup (with a newer IdeaVIM version) it does also not work.

Unfortunately I can't update this dependency now as they have changed some internal code that the plugin relies on, see [here](https://youtrack.jetbrains.com/issue/VIM-3085/Make-VimTypedActionHandler-and-VimShortcutKeyAction-accessible-again). I'll see what I can find out

**Comment by TheBlob42** [comment]
It doesn't recognize the `i` in `ysiw` as the start of a motion, ignores it (since you've set the ProcessUnknownMappings option to `false`) and the next key press (here `w`) is executed like a new mapping or key press. This is something that should be fixed, but so far I don't know how.

I just document my findings here for reference:
I can find the surround mappings when processing the key presses, but I'm missing a way to identify that they are expecting a "motion" argument next (e.g. `iw`, `a(`, etc.) as the MappingMode is still on NORMAL. I saw that the Surround Extension executions the `operatorfunc`, but I can't find any "evidence" that this happened. Need another look if there is a way to identify such cases.

**Comment by TheBlob42** [comment]
Ok I think I found a way to catch this case (and others that might have the same issue).

But I am not 100% sure if this does not also catch mappings that it shouldn't in an unforeseeable way, therefore I would love to get some feedback and testing at best with a lot of custom mappings and extensions enabled to see if another issue can be provoked. The fix is on the `develop` branch

**Comment by TheBlob42** [comment]
Sorry for the long wait. The release is on its way (you can already manually install the latest version `0.10.2`)
