### ISSUE TITLE
Extend to support multi-chord keymap shortcuts

### ISSUE THREAD

**Issue by Josh-Piper** [TheBlob42/idea-which-key#49]
It would be awesome if this plugin also worked for the IntelliJ multi-chord keystroke keymaps.

**Comment by TheBlob42** [comment]
This might be worth its own plugin :smile: 
I have no knowledge how to access these keybindings, but since the code for this plugin is highly specific towards IdeaVIM it would be a completely new integration. I am also not using multi-chord "native" keybindings from Intellij myself. Therefore I will not work on the support here, but I am happy to accept (and discuss) contributions
